server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/note_vault_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      indent_output: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG

app:
  encryption:
    secret: bQ4okh6Mke4FzCfqG7Xz5b7D2NZVgDn9xqfS+R+Oh0A=
